#!/usr/bin/env python3

import sys
import argparse
from biogl import rev_comp
from fileinput import input as finput

parser = argparse.ArgumentParser(
    description='reverse-complement a nucleotide sequence',
    formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument(
    'seq',
    help='nucleotide sequence to be reverse-complemented'
),
parser.add_argument(
    '--no_mask',
    action='store_true',
    help='don\'t mask non-ACTG characters with N',
    default=False),
parser.add_argument(
    '--no_lower',
    action='store_true',
    help='consider lowercase input invalid (will still reverse)',
    default=False,
)

args = parser.parse_args()

MASK = not args.no_mask
KEEP_LOWER = not args.no_lower

for l in finput(args.seq):
    l = l.strip()
    if l.startswith('>'):
        print(l)
    else:
        r_seq = rev_comp(l, mask=MASK, use_lower=KEEP_LOWER)
        print(r_seq)


sys.exit(0)